$m1e_path = "C:\Users\hellw\OneDrive - Colorado Community College System\COM120\Essays\Module-1\M1E_Picture-Perfect"

Write-Host 'Cleaning LaTeX Project'
Remove-Item "$m1e_path\*_temp.tex"
Remove-Item "$m1e_path\*.aux"
Remove-Item "$m1e_path\*.4ct"
Remove-Item "$m1e_path\*.4tc"
Remove-Item "$m1e_path\*.dvi"
Remove-Item "$m1e_path\*.idv"
Remove-Item "$m1e_path\*.lg"
Remove-Item "$m1e_path\*.out.ps"
Remove-Item "$m1e_path\*.tmp"
Remove-Item "$m1e_path\*.xref"
Remove-Item "$m1e_path\*.bbl"
Remove-Item "$m1e_path\*.bcf"
Remove-Item "$m1e_path\*.blg"
Remove-Item "$m1e_path\*.idx"
Remove-Item "$m1e_path\*.ind"
Remove-Item "$m1e_path\*.lof"
Remove-Item "$m1e_path\*.lot"
Remove-Item "$m1e_path\*.out"
Remove-Item "$m1e_path\*.toc"
Remove-Item "$m1e_path\*.acn"
Remove-Item "$m1e_path\*.acr"
Remove-Item "$m1e_path\*.alg"
Remove-Item "$m1e_path\*.glg"
Remove-Item "$m1e_path\*.glo"
Remove-Item "$m1e_path\*.gls"
Remove-Item "$m1e_path\*.ist"
Remove-Item "$m1e_path\*.fls"
Remove-Item "$m1e_path\*.log"
Remove-Item "$m1e_path\*.fdb_latexmk"
Remove-Item "$m1e_path\*.synctex.gz"
Remove-Item "$m1e_path\*.lol"
Remove-Item "$m1e_path\*.run.xml"
Remove-Item "$m1e_path\*.pdf"

Write-Host 'Building LaTeX Project'
& 'C:\Program Files\MiKTeX\miktex\bin\x64\latexmk.exe' '-pdf' '-pdflatex="pdflatex -interaction=nonstopmode"'

Write-Host 'Moving File to out/ASHELLWIG_M1E_Picture-Perfect.pdf'
Move-Item -Path "$m1e_path\main.pdf" -Destination "$m1e_path\out\ASHELLWIG_M1E_Picture-Perfect.pdf"

Write-Host 'Cleaning Project Directory'
Remove-Item "$m1e_path\*_temp.tex"
Remove-Item "$m1e_path\*.aux"
Remove-Item "$m1e_path\*.4ct"
Remove-Item "$m1e_path\*.4tc"
Remove-Item "$m1e_path\*.dvi"
Remove-Item "$m1e_path\*.idv"
Remove-Item "$m1e_path\*.lg"
Remove-Item "$m1e_path\*.out.ps"
Remove-Item "$m1e_path\*.tmp"
Remove-Item "$m1e_path\*.xref"
Remove-Item "$m1e_path\*.bbl"
Remove-Item "$m1e_path\*.bcf"
Remove-Item "$m1e_path\*.blg"
Remove-Item "$m1e_path\*.idx"
Remove-Item "$m1e_path\*.ind"
Remove-Item "$m1e_path\*.lof"
Remove-Item "$m1e_path\*.lot"
Remove-Item "$m1e_path\*.out"
Remove-Item "$m1e_path\*.toc"
Remove-Item "$m1e_path\*.acn"
Remove-Item "$m1e_path\*.acr"
Remove-Item "$m1e_path\*.alg"
Remove-Item "$m1e_path\*.glg"
Remove-Item "$m1e_path\*.glo"
Remove-Item "$m1e_path\*.gls"
Remove-Item "$m1e_path\*.ist"
Remove-Item "$m1e_path\*.fls"
Remove-Item "$m1e_path\*.log"
Remove-Item "$m1e_path\*.fdb_latexmk"
Remove-Item "$m1e_path\*.synctex.gz"
Remove-Item "$m1e_path\*.lol"
Remove-Item "$m1e_path\*.run.xml"
